consultations/urls.py
from django.conf.urls import url
from consultations import views

app_name = 'consultations'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^consultation/(?P<pk>\d+)/$', views.consultation, name = 'consultation'),
    url(r'^thanks/(?P<pk>\d+)/$', views.thanks, name = 'thanks'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    # called by the join page
    path('create_inactive_member/', views.create_inactive_member, name='create_inactive_member'),
    
    # called by GDPR tool
    path('anonymise_member/', views.anonymise_member, name='anonymise_member'),
    
    # activation
    path('request_activation_email/', views.request_activation_email, name='request_activation_email'),
    path('confirm_activation_email/', views.confirm_activation_email, name='confirm_activation_email'),
    path('activate/<slug:activation_key>/', views.activate, name='activate'),
    
    # profile
    path('profile/', views.profile, name='profile'),
    path('change_login_email/', views.change_login_email, name='change_login_email'),
    path('login_email_verification_sent/', views.login_email_verification_sent, name='login_email_verification_sent'),
    path('verify_login_email/<slug:login_email_verification_key>/', views.verify_login_email, name='verify_login_email'),
    
    # update_subscriptions
    path('update_subscriptions/', views.update_subscriptions, name='update_subscriptions'),
    path('token_subs/<uuid:token>/', views.user_token_subs, name='user_token_subs'),

    # expose information to member
    path('memberinfo', views.ReturnMemberInfo.as_view()),

    # update details campaign
    path('update_details/<int:page>/', views.update_details, name='update_details'),
    
    # NationBuilder webhooks
    path('nation_builder_person_created/', views.nation_builder_person_created, name='nation_builder_person_created'),
    path('nation_builder_person_updated/', views.nation_builder_person_updated, name='nation_builder_person_updated'),
    path('nation_builder_person_deleted/', views.nation_builder_person_deleted, name='nation_builder_person_deleted'),
    path('nation_builder_person_merged/', views.nation_builder_person_merged, name='nation_builder_person_merged'),
]

mxv/urls.py
from . import views
from . import forms
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse, HttpResponseRedirect

urlpatterns = [
    # landing page
    url(r'^$', views.index, name='index'),
    
    # admin
    url(r'^admin/', include('members.adminurls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),

    # redirect to react app    
    url(r'^app/', views.react),
    url(r'^api-auth/', include('rest_framework.urls')),

    # error testing
    url(r'^error/$', views.error, name='error'),
    
    # for various app urls.py

    # members
    url(r'^members/', include('members.urls')),
    url(r'^members/password_reset/$', views.ExtraContextPasswordResetView.as_view(
        form_class=forms.ActivationEmailPasswordResetForm), name='password_reset'),
    url(r'^members/login/$', auth_views.LoginView.as_view(
        form_class=forms.ActivationEmailAuthenticationForm), name='login'),
    url(r'^members/', include('django.contrib.auth.urls')),
    # q&a
    url(r'^questions/', include('questions.urls')),
    # lobbying 
    url(r'^lobby/', include('lobby.urls')),
    # groups
    url(r'^groups/', include('groups.urls')),
    # publications/petitions/cms
    url(r'^publications/', include('petitions.urls')),
    # democracy review
    url(r'^review/', include('review.urls')), 
    # GDPR
    url(r'^reconsent/$', views.reconsent, name='reconsent'), 
    url(r'^reconsent_complete/$', views.reconsent_complete, name='reconsent_complete'),
    # voting intentions
    url(r'^voting_intentions/', include('voting_intentions.urls')),
    # consultations
    url(r'^consultations/', include('consultations.urls')),
    # short URL redirects so that the links can be used in SMS
    url(r'^u/(?P<unique_token>[a-zA-Z0-9]+)/$',
        views.redirect_to_update_details, name='redirect_to_update_details'),

    # for martor, the markdown editor
    url(r'^martor/', include('martor.urls')),
    # task queueing
    url(r'^django-rq/', include('django_rq.urls')),

    # robots.txt
    url(r'^robots.txt', lambda x: HttpResponse(
        "User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),
    
    # humans.txt
    url(r'^humans.txt', lambda x: HttpResponseRedirect("https://gitlab.com/momentum-tech-collective/mxv")),

    # Imprint
    url(r'^imprint/', views.imprint)
]

if settings.PRIMARIES_VISIBLE:
    urlpatterns += [
        url(r'^primaries/', include('primaries.urls')),
    ]

admin.autodiscover()
admin.site.enable_nav_sidebar = False

questions/urls.py
from django.conf.urls import url
from questions import views

app_name = 'questions'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'info', views.info, name='info'),
    url(r'^question/(?P<pk>\d+)/$', views.answers, name = 'answers'),
    url(r'^vote/(?P<pk>\d+)/$', views.vote, name = 'vote'),
    url(r'^unvote/(?P<pk>\d+)/$', views.unvote, name='unvote')
]

mxv/forms.py
from django import forms
from mxv.models import Reconsent, EmailSettings
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.contrib.auth import authenticate
from members.models import Member
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator

class ReconsentForm(forms.ModelForm):    
    class Meta:
        model = Reconsent
        fields = ['email']

def SendActivationEmailToInactiveMember(request, email):

    # if the username relates to an inactive member...
    try:
        inactive_member = Member.objects.get(email = email, is_active = False)
    except:
        inactive_member = None
    if inactive_member:
        
        # send an activation email
        activation_email = EmailSettings.get_solo().activation_email
        if activation_email:
            try:
                activation_email.send_to(request, [inactive_member.email])
            except:
                pass

class ActivationEmailAuthenticationForm(AuthenticationForm):
    
    # gets the request
    def __init__(self, *args, **kwargs):
        super(ActivationEmailAuthenticationForm, self).__init__(*args, **kwargs)
        self.request = kwargs.pop('request', None)

    # copied from AuthenticationForm but modified to send an activation email to inactive members
    def clean(self):
        
        # if the username/password are present...
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username is not None and password:
            
            # but not valid...
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                
                # send an activation email if inactive member
                SendActivationEmailToInactiveMember(self.request, username)
                
                # raise the invalid login error
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                # allow further checks on the user
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

class EmailForm(forms.Form):    
    email = forms.EmailField()

class ActivationEmailPasswordResetForm(PasswordResetForm):
    
    # sends an activation email if the email relates to an inactive member
    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None,
             extra_email_context=None):
        
        email = self.cleaned_data["email"]

        # send an activation email if inactive member
        SendActivationEmailToInactiveMember(request, email)
              
        # usual logic
        super(ActivationEmailPasswordResetForm, self).save(domain_override, 
                                                           subject_template_name, 
                                                           email_template_name, 
                                                           use_https, 
                                                           token_generator, 
                                                           from_email, 
                                                           request, 
                                                           html_email_template_name, 
                                                           extra_email_context)

mxv/views.py
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.views import PasswordResetView
from django.http import Http404
from django.conf import settings
from review.models import TrackVoting
from django.shortcuts import render, redirect
from mxv.models import Reconsent
from mxv.forms import ReconsentForm
from django.contrib import messages
from django.http.response import HttpResponseRedirect, HttpResponseServerError
from django.urls.base import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import ensure_csrf_cookie
from mxv.nation_builder import NationBuilder
from members.models import ensure_nationbuilder_person
from groups.models import Group, GroupStatusType
from members.models import *
import time
import logging
import requests

logger = logging.getLogger()
logger.level = logging.DEBUG

def member_is_dpa(request):
    if not Group.objects.filter(dpa=request.user).exists():
        return False
    # TODO: will crash if single DPA has more than one group, shouldn't happen in prod
    group = Group.objects.get(dpa=request.user)
    return group.status in {GroupStatusType.Verified, GroupStatusType.ScotlandVerified, GroupStatusType.WalesVerified}

# landing page
@login_required
def index(request):
    template = loader.get_template('mxv/index.html')
    
    context = {
        'show_track3_voting': settings.TRACK3_VOTING_VISIBLE_TO_NON_STAFF or request.user.is_staff,
        'show_consultations': settings.CONSULTATIONS_VISIBLE_TO_NON_STAFF or request.user.is_staff,
        'show_members_card': settings.MEMBERSHIP_CARD_VISIBLE_TO_NON_STAFF or request.user.is_staff,
        'show_questions': settings.QUESTIONS_VISIBLE_TO_NON_STAFF or request.user.is_staff,
        'show_primaries': settings.PRIMARIES_VISIBLE,
        'show_inbox': settings.INBOX_VISIBLE,
        'show_update_subs': request.user.is_superuser or settings.UPDATE_SUBS_VISIBLE_TO_NON_STAFF,
        'track3_voting': TrackVoting.objects.filter(pk=3).first(),
        'member_logged_in': request.user.is_authenticated,
        'member_is_dpa': member_is_dpa(request),
        'show_policy_primary_submissions': settings.POLICY_PRIMARY_SUBMISSIONS_VISIBLE
    }

    # return NB person
    person = ""
    if settings.MEMBERSHIP_CARD_VISIBLE_TO_NON_STAFF == True:
        nb = NationBuilder()
        member = request.user
        ensure_nationbuilder_person(nb, member)
        nb_person = NationBuilderPerson.objects.get(id=member.nationbuilderperson_id)
        nb_context = {
            'nb_membershipno': nb_person.membership_number,
            'nb_email': nb_person.email,
            'nb_address1': nb_person.primary_address1,
            'nb_address2': nb_person.primary_address2,
            'nb_address3': nb_person.primary_address3,
            'nb_address_city': nb_person.primary_city,
            'nb_address_postcode': nb_person.primary_postcode
        }

        if nb_person.first_name and nb_person.last_name:
            full_name = f'{nb_person.first_name} {nb_person.last_name}'
            nb_context.setdefault('nb_full_name', full_name)

        context.update(nb_context)

    return HttpResponse(template.render(context, request))

# pass the site names to the password reset context
class ExtraContextPasswordResetView(PasswordResetView):
    extra_email_context = {
         'site_name_short': settings.SITE_NAME_SHORT,
         'site_name_long': settings.SITE_NAME_LONG,
         }

# raises an error if allowed
def error(request):
    if settings.ALLOW_ERROR_URL:
        raise Exception('error test')
    else:
        raise Http404('not found')
    
# returns the IP address from a request
def ip_from_request(request):
    
    # use the forwarded address if behind a router
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return(x_forwarded_for.split(',')[-1].strip())
    else:
        return(request.META.get('REMOTE_ADDR'))
        
# re-consent page
def reconsent(request):
    
    # if post...
    if request.method == 'POST':
        form = ReconsentForm(request.POST)
        
        # just complete if the re-consent already exists
        exists = Reconsent.objects.filter(email = form.data['email'])
        if exists:
            return redirect('reconsent_complete')
        
        # if valid post for new email...
        if form.is_valid():
            
            # save the email and IP
            reconsent = form.save(commit = False)
            reconsent.ip_address = ip_from_request(request)
            reconsent.save()
            
            # complete
            return redirect('reconsent_complete')
        
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
            
    else:
        # if there is an email parameter...
        email = request.GET.get('email', None)
        if email:
            
            # if the email does not already exist...
            exists = Reconsent.objects.filter(email = email)
            if not exists:
                
                # save the email and IP
                reconsent = Reconsent()
                reconsent.email = email
                reconsent.ip_address = ip_from_request(request)
                reconsent.save()
            
            # complete
            return redirect('reconsent_complete')
        else:
            # no parameter so allow user to enter an email
            form = ReconsentForm()
    
    return render(request, 'mxv/new_reconsent.html', { 
        'title' : 'Re-consent',
        'form' : form})
    
# re-consent complete page
def reconsent_complete(request):
    return render(request, 'mxv/reconsent_complete.html', { 
        'title' : 'Re-consent complete'})
    
# /u/[unique_token] redirects to /members/update_details/1?unique_token=[unique_token]
def redirect_to_update_details(request, unique_token):
    return HttpResponseRedirect('%s?unique_token=%s' % (reverse('members:update_details', kwargs = {'page': 1}), unique_token))

@ensure_csrf_cookie
def react(request):
    return render(request, 'build/index.html', {})

# Pass the imprint text from MoApp. More or less just copied over from yl,
def imprint(request):
    try:
        response = requests.get('https://api.peoplesmomentum.com/imprint', timeout=10)
        if response.status_code == 200:
            return HttpResponse(response.text, content_type='text/plain; charset=UTF-8')
        else:
            logging.error(response.text)
            return HttpResponseServerError()
    except Exception as e:
        logging.error(e)
        return HttpResponseServerError()

mxv/templates/mxv/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <title>{{ site_name_long }} - {% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://use.typekit.net/tii8vev.css">        
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
        <link rel="manifest" href="{% static 'site.webmanifest' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">  
        <meta name="msapplication-TileColor" content="#e201613">
        <meta name="theme-color" content="#e201613">

        <script src="https://use.fontawesome.com/fe32e441c1.js"></script>

        {% block head %}{% endblock %}
        {% include "mxv/meta_tags.html" %}
        {% include "mxv/tracking_tags.html" %}
    </head>
    <body>
        {% block nav %}{% endblock %}
        {% block content_area %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

mxv/templates/mxv/base_nav.html
{% extends "mxv/base.html" %}
{% block nav %}
    {% include "mxv/navbar.html" %}
    {% include "mxv/messages.html" %}      
    <div class="container-full m-0 bg-light py-2" style="border-bottom: thin solid#E5E5E5;">
        <div class="pseudocontainer">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <ol class="breadcrumb p-0 m-0">
                        {% block breadcrumb %}{% endblock %}
                    </ol>
                </div>
            </div>
        </div>
    </div> 
{% endblock %}
{% block content_area %}
    <div class="container">
    {% block content %}{% endblock %}
    <br/><br/>
    {% include "mxv/footer.html" %}
    </div>   
{% endblock %}

mxv/templates/mxv/base_two-frame.html
{% extends "mxv/base.html" %}
    
{% load static %}

{% block head%}
<link rel="stylesheet" href="{% static 'css/two-frame.css' %}">
{% endblock head %}

{% block content_area %}
    <div id="two-frame">
        <div class="row no-gutters">
            <div class="col-sm-12 col-md-6 img-wrapper">
                <img id="brand" class="m-4" src={% static 'mxv/images/logo.png' %}>
            </div>
            <div class="col-sm-12 col-md-6 d-grid justify-content-center copy-wrapper">
                <div class="d-flex justify-content-start flex-column mx-5 mt-5 mb-3">
                    {% block content %}{% endblock %}
                </div>
                <div class="d-flex justify-content-end flex-column mx-5 mb-5">
                    <p id="imprint" class="small">
                        ...
                    </p>
                </div>
            </div>
        </div>
    </div>
    <script>
      {
        const getImprint = async () => {
          try {
            const res = await fetch('/imprint')
            const text = await res.text()
            document.getElementById('imprint').textContent = text
          } catch (e) {
            console.log('Error:', e)
          }
        }

        getImprint()
      }
    </script>
{% endblock content_area %}

mxv/templates/mxv/breadcrumbs.html
<div class="container-full m-0 bg-light py-2" style="border-bottom: thin solid#E5E5E5;">
    <div class="pseudocontainer">
        <div class="row">
            <div class="col-12 col-lg-6">
                <ol class="breadcrumb p-0 m-0">
                  {% for item in breadcrumbs %}
                  {% endfor %}
                </ol>
            </div>
        </div>
    </div>
</div>

mxv/templates/mxv/index.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Home{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Home</li>
{% endblock %}

{% block content %}
    {% if show_members_card %}
    <div class="row justify-content-center">
        <div class="col-sm-12 col-lg-6">
            <h2>Welcome to My Momentum, the digital platform that enables members to learn, organise and make decisions
                together.</h2>
        </div>    
    </div>

    <div class="row justify-content-center mb-0">

        <div class="col-sm-12 col-lg-6">
            <div class="card" id="membership-card">
                <h2 class="p-0" id="mc_fullname">
                {% if nb_full_name %}
                    {{ nb_full_name }}
                {% endif %}
                </h2> 
    
                <p class=" m-0 p-0 mc_address">{{ nb_address1 }}<br/>
                    {% if nb_address2 %}{{ nb_address2 }}<br/>{% endif %}
                    {% if nb_address3 %}{{ nb_address3 }}<br/>{% endif %}
                    {{ nb_address_city }}, {{ nb_address_postcode }}
                </p>
                <p class=" m-0 p-0" id="mc_contact">
                    <span class="primary-lighter-30">Email:</span> {{ nb_email }}<br/>
                    {% if nb_phone %} <span class="primary-lighter-30">Tel:</span> {{ nb_phone }} {% endif %}
                </p>
                <p class=" m-0 p-0" id="mc_memno">
                 {% if nb_membershipno %}
                    <span class="primary-lighter-30 m-0 p-0 label-1">
                    Membership no.:
                    </span>
                    <br>
                    {{ nb_membershipno }}
                {% endif %}
                </p>
            </div>
            <h4 class="my-2"><a href="{% url 'members:profile' %}">Update details ↷</a></h4>
            {% if show_update_subs %}
            <h4 class="my-2"><a href="{% url 'members:update_subscriptions' %}">Update subscriptions ↷</a></h4>
            {% endif %}
        </div>

    </div>

    {% endif %}

    <div class="row justify-content-center mt-0">

        <div class="col-sm-12 col-lg-6 ">
            <hr class="hr-primary mb-1"/>
            <h3 class="red">What's on</h3>
        </div>

    </div>

    {% if member_logged_in %}

        {% if member_is_dpa %}

            {% if show_policy_primary_submissions %}

        <div class="row justify-content-center mb-4">
        
            <div class="col-sm-12 col-lg-6">
                <div class="card">
                    <img class="img-fluid img-homepage" src="{% static 'mxv/images/conference.jpg' %}" />
                    <div class="card-body">
                        <div class="card-row-title">
                            <h2>Submit a motion for Labour Party conference</h2>
                        </div>
                        <div class="card-row-body">
                            <p class="body-sm-1">Your submitted motion should have been agreed by your local group at a democratic meeting.</p>
                        </div>
                    </div>
                    <div class="card-button-wrapper">
                        <a href="/app/motionsubmission" class="btn btn-outline-primary btn-block">Submit your group's motion</a>
                    </div>
                </div>
            </div>
        
        </div>

            {% endif %}
        
        {% endif %}

        {% if show_policy_primary_submissions %}

        <div class="row justify-content-center mb-4">
        
            <div class="col-sm-12 col-lg-6">
                <div class="card">
                    <img class="img-fluid img-homepage" src="{% static 'mxv/images/cardvote.jpg' %}" />
                    <div class="card-body">
                        <div class="card-row-title">
                            <h2>Submit a rule change for Labour Party conference</h2>
                        </div>
                        <div class="card-row-body">
                            <p class="body-sm-1">Members can submit rule change motions for consideration by Momentum</p>
                        </div>
                    </div>
                    <div class="card-button-wrapper">
                        <a href="/app/rulechange" class="btn btn-outline-primary btn-block">Propose a rule change</a>
                    </div>
                </div>
            </div>
        
        </div>

        {% endif %}

        {% if show_primaries %}

        <div class="row justify-content-center mb-4">
        
            <div class="col-sm-12 col-lg-6">
                <div class="card">
                    <img class="img-fluid img-homepage" src="{% static 'mxv/images/primaries.png' %}" />
                    <div class="card-body">
                        <div class="card-row-title">
                            <h2>Open primaries</h2>
                        </div>
                        <div class="card-row-body">
                            <p class="body-sm-1">Choose which policies we support at Labour Conference or who Momentum endorses in key elections.</p>
                        </div>
                    </div>
                    <div class="card-button-wrapper">
                        <a href="/app/primaries" class="btn btn-outline-primary btn-block">View</a>
                    </div>
                </div>
            </div>
        
        </div>
        
        {% endif %}

        <div class="row justify-content-center">

            <div class="col-sm-12 col-lg-6">
                <hr class="hr-primary mb-1">
                <h3 class="red">Past projects</h3>
            </div>

        </div>

        {% if show_questions %}

        <div class="row justify-content-center mb-4">

            <div class="col-sm-12 col-lg-6">
                <div class="card">
                    <img class="img-fluid img-homepage" src="{% static 'mxv/images/conversation.jpg' %}"/>
                    <div class="card-body">
                        <div class="card-row-title">
                            <h2>Questions for candidates</h2>
                        </div>
                        <div class="card-row-body">
                            <p class="body-sm-1">Your chance to ask the NCG candidates about their plans for the movement</p>
                        </div>
                    </div>
                    <div class="card-button-wrapper">
                        <a href="{% url 'questions:index' %}" class="btn btn-outline-primary btn-block">View</a>
                    </div>
                </div>
            </div>

        </div>
        {% endif %}
        
        {% if show_consultations %}
        
        <div class="row justify-content-center">

            <div class="col-sm-12 col-lg-6 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="card-row-title">
                            <h2>Previous consultations</h2>
                        </div>
                        <div class="card-row-body">
                            <p class="body-sm-1">We have run consultations on subjects that are important to our members.  We've archived results here.</p>
                        </div>
                    </div>
                    <div class="card-button-wrapper">
                        <a href="{% url 'consultations:index' %}" class="btn btn-outline-primary btn-block">View</a>
                    </div>
                </div>
            </div>

        </div>

        {% endif %}
        
        {% else %}
        
        <div class="row justify-content-center">
        
            <div class="col-sm-12">
                <p>If you’re a member of Momentum but haven't activated your account yet, just check your email for your activation link from <a href="mailto:mymomentum@peoplesmomentum.com">mymomentum@peoplesmomentum.com</a> or <a href="{% url 'members:request_activation_email' %}">request a new account activation email</a>.</p>
                <p>Not a member of Momentum yet? <a href="https://join.peoplesmomentum.com/" target="_blank">Sign up today</a> and join the discussion.</p>
            </div>
        
        </div>
        
        {% endif %}
    
    </div>
{% endblock %}

mxv/templates/mxv/messages.html
{% load static %}
{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock messages %}

mxv/templates/mxv/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom: thin solid #E5E5E5;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static "mxv/images/logo.png" %}" alt="Logo" style="max-width: 150px;"/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="nav-item active nav-link dropdown-toggle primary" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% if profiles_visible_to_non_staff or user.is_superuser %}
                        <li class="nav-item"><a class="nav-link p-2" href="{% url 'members:profile' %}">Profile</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link p-2" href="{% url 'password_change' %}">Change Password</a></li>
                        <li class="nav-item"><a class="nav-link p-2" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% if show_inbox %}
                    <li class="nav-item"><a class="nav-link" href="/app/inbox">Inbox</a></li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="nav-item"><a class="nav-link" href="/admin">Admin</a></li>
                {% endif %}
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'password_reset' %}">Reset Password</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ join_url }}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>