mxv/urls.py
from . import views
from . import forms
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse, HttpResponseRedirect

urlpatterns = [
    # landing page
    url(r'^$', views.index, name='index'),
    
    # admin
    url(r'^admin/', include('members.adminurls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),

    # redirect to react app    
    url(r'^app/', views.react),
    url(r'^api-auth/', include('rest_framework.urls')),

    # error testing
    url(r'^error/$', views.error, name='error'),
    
    # for various app urls.py

    # members
    url(r'^members/', include('members.urls')),
    url(r'^members/password_reset/$', views.ExtraContextPasswordResetView.as_view(
        form_class=forms.ActivationEmailPasswordResetForm), name='password_reset'),
    url(r'^members/login/$', auth_views.LoginView.as_view(
        form_class=forms.ActivationEmailAuthenticationForm), name='login'),
    url(r'^members/', include('django.contrib.auth.urls')),
    # q&a
    url(r'^questions/', include('questions.urls')),
    # lobbying 
    url(r'^lobby/', include('lobby.urls')),
    # groups
    url(r'^groups/', include('groups.urls')),
    # publications/petitions/cms
    url(r'^publications/', include('petitions.urls')),
    # democracy review
    url(r'^review/', include('review.urls')), 
    # GDPR
    url(r'^reconsent/$', views.reconsent, name='reconsent'), 
    url(r'^reconsent_complete/$', views.reconsent_complete, name='reconsent_complete'),
    # voting intentions
    url(r'^voting_intentions/', include('voting_intentions.urls')),
    # consultations
    url(r'^consultations/', include('consultations.urls')),
    # short URL redirects so that the links can be used in SMS
    url(r'^u/(?P<unique_token>[a-zA-Z0-9]+)/$',
        views.redirect_to_update_details, name='redirect_to_update_details'),

    # for martor, the markdown editor
    url(r'^martor/', include('martor.urls')),
    # task queueing
    url(r'^django-rq/', include('django_rq.urls')),

    # robots.txt
    url(r'^robots.txt', lambda x: HttpResponse(
        "User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),
    
    # humans.txt
    url(r'^humans.txt', lambda x: HttpResponseRedirect("https://gitlab.com/momentum-tech-collective/mxv")),

    # Imprint
    url(r'^imprint/', views.imprint)
]

if settings.PRIMARIES_VISIBLE:
    urlpatterns += [
        url(r'^primaries/', include('primaries.urls')),
    ]

admin.autodiscover()
admin.site.enable_nav_sidebar = False

review/urls.py
from django.conf.urls import url

from review import views

app_name = 'review'
urlpatterns = [
    # index
    url(r'^$', views.index, name='index'),
    #tracks
    url(r'^track/(?P<pk>\d+)/$', views.track, name = 'track'),
    # themes
    url(r'^theme/(?P<pk>\d+)/$', views.theme, name = 'theme'),
    # proposals
    url(r'^theme/(?P<pk>\d+)/new_proposal/$', views.new_proposal, name = 'new_proposal'),
    url(r'^theme/(?P<pk>\d+)/proposal_submitted/$', views.proposal_submitted, name = 'proposal_submitted'),
    url(r'^proposal/(?P<pk>\d+)/$', views.proposal, name = 'proposal'),
    url(r'^proposal/(?P<pk>\d+)/edit/$', views.edit_proposal, name = 'edit_proposal'),
    url(r'^proposal/(?P<pk>\d+)/delete/$', views.delete_proposal, name = 'delete_proposal'),
    url(r'^proposal/(?P<pk>\d+)/moderate/$', views.moderate_proposal, name = 'moderate_proposal'),
    # amendments
    url(r'^proposal/(?P<pk>\d+)/new_amendment/$', views.new_amendment, name = 'new_amendment'),
    url(r'^amendment/(?P<pk>\d+)/$', views.amendment, name = 'amendment'),
    url(r'^amendment/(?P<pk>\d+)/edit/$', views.edit_amendment, name = 'edit_amendment'),
    url(r'^amendment/(?P<pk>\d+)/delete/$', views.delete_amendment, name = 'delete_amendment'),
    url(r'^amendment/(?P<pk>\d+)/moderate/$', views.moderate_amendment, name = 'moderate_amendment'),
    # comments
    url(r'^proposal/(?P<pk>\d+)/new_comment/$', views.new_comment, name = 'new_comment'),
    url(r'^comment/(?P<pk>\d+)/$', views.comment, name = 'comment'),
    url(r'^comment/(?P<pk>\d+)/moderate/$', views.moderate_comment, name = 'moderate_comment'),
    # support pages
    url(r'^help/$', views.help, name = 'help'),
    url(r'^rules/$', views.rules, name = 'rules'),
    url(r'^faq/$', views.faq, name = 'faq'),
    url(r'^moderation/$', views.moderation, name = 'moderation'),
    url(r'^guide/$', views.guide, name = 'guide'),
    #track voting
    url(r'^voting/$', views.voting, name = 'voting'),
    url(r'^track_voting/(?P<pk>\d+)/$', views.track_voting, name = 'track_voting'),
    url(r'^track_voting/(?P<pk>\d+)/vote_submitted/$', views.vote_submitted, name = 'vote_submitted'),
]

review/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Track, Theme, Proposal, Amendment, Comment, TrackVoting
from django.db.models import Count, Q
from review.forms import EditProposalForm, ProposalForm, DeleteProposalForm, AmendmentForm, EditAmendmentForm, DeleteAmendmentForm, EditCommentForm, ModerationRequestForm, CommentForm, VoteForm
from django.contrib import messages
from datetime import date
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

@login_required
def index(request):
    today = date.today()
    live_tracks = Track.objects.order_by('display_order').filter(
        Q(submission_start__lte = today, submission_end__gte = today) | 
        Q(nomination_start__lte = today, nomination_end__gte = today))
    live_track_text = ''
    if live_tracks.count() == 1:
        live_track_text = ', with %s currently live' % live_tracks.first().name
    elif live_tracks.count() > 1:
        live_track_text = ', with %s currently live' % ' and '.join(track.name for track in live_tracks)
    return render(request, 'review/index.html', { 
        'tracks' : Track.objects.all().order_by('display_order'),
        'live_track_text': live_track_text,
        'track_votings': TrackVoting.objects.all() })

@login_required
def track(request, pk):
    track = get_object_or_404(Track, pk = pk)
    try:
        track_voting = track.voting
    except ObjectDoesNotExist:
        track_voting = None
    return render(request, 'review/tracks/track.html', { 
        'track' : track, 
        'themes': track.themes.order_by('display_order'),
        'show_voting': track_voting and track_voting.pk == 3 and (settings.TRACK3_VOTING_VISIBLE_TO_NON_STAFF or request.user.is_staff),
        'track_voting': track_voting })
    
@login_required
def theme(request, pk):
    theme = get_object_or_404(Theme, pk = pk)
    user_proposal = theme.proposals.filter(created_by = request.user).first()
    return render(request, 'review/themes/theme.html', { 
        'theme' : theme, 
        'proposals': theme.proposals.annotate(nomination_count = Count('nominations')).order_by('-nomination_count', '-created_at', 'pk'),
        'user_proposal': user_proposal })

@login_required
def proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
    moderation = request.user.moderation_requests.filter(proposal = proposal).first()
    
    # if valid post...
    if request.method == 'POST':
        form = ProposalForm(request.POST)
        if form.is_valid():        
            
            # nominate if allowed
            if 'nominate' in request.POST and proposal.theme.track.nominations_currently_allowed():
                for nomination in request.user.nominations.filter(proposal__theme = proposal.theme):
                    nomination.delete()
                proposal.nominations.create(proposal = proposal, nominated_by = request.user)
                
            # clear nomination if allowed
            if 'clear_nomination' in request.POST and proposal.theme.track.nominations_currently_allowed():
                nomination = proposal.nominations.filter(nominated_by = request.user, proposal = proposal).first()
                if nomination:
                    nomination.delete()
                    
            # cancel moderation if moderation request exists
            if 'cancel_moderation' in request.POST and moderation:
                moderation.delete()
                
            # turn the moderation request into a comment
            if 'turn_moderation_into_comment' in request.POST and moderation:
                proposal.comments.create(
                    proposal = moderation.proposal, 
                    created_by = moderation.requested_by, 
                    created_at = moderation.requested_at, 
                    text = moderation.reason)
                moderation.delete()
                    
            return redirect('review:proposal', pk = proposal.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ProposalForm(instance = proposal)

    return render(request, 'review/proposals/proposal.html', { 
        'proposal' : proposal,
        'proposal_urls' : proposal.urls.order_by('pk'),
        'amendments' : proposal.amendments.order_by('-created_at'),
        'comments' : proposal.comments.order_by('-created_at'),
        'user_nominated': request.user.nominations.filter(proposal = proposal).exists(),
        'moderation': moderation,
        'form': form })

@login_required
def new_proposal(request, pk):
    theme = get_object_or_404(Theme, pk = pk)
    
    # redirect if submissions are not allowed or user already has a proposal in this theme
    if not theme.track.nominations_currently_allowed() or request.user.proposals.filter(theme = theme).exists():
        return redirect('review:theme', pk = theme.pk)

    # if valid post...
    if request.method == "POST":
        form = EditProposalForm(request.POST)
        if form.is_valid():
            
            # create proposal
            proposal = form.save(commit = False)
            proposal.theme = theme
            proposal.created_by = request.user
            proposal.save()
            
            return redirect('review:proposal_submitted', pk = theme.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = EditProposalForm()
        
    return render(request, 'review/proposals/new_proposal.html', { 
        'theme' : theme,
        'form' : form })

@login_required
def proposal_submitted(request, pk):
    theme = get_object_or_404(Theme, pk = pk)
    return render(request, 'review/proposals/proposal_submitted.html', { 
        'theme' : theme })

@login_required
def edit_proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
    
    # redirect if moderated, submissions are not allowed or incorrect user
    if proposal.moderated() or not proposal.theme.track.submissions_currently_allowed() or request.user != proposal.created_by:
        return redirect('review:proposal', pk = proposal.pk)

    # if valid post...
    if request.method == "POST":
        form = EditProposalForm(request.POST, instance = proposal)
        if form.is_valid():
            
            # save the proposal
            proposal = form.save()
            
            return redirect('review:proposal', pk = proposal.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = EditProposalForm(instance = proposal)
        
    return render(request, 'review/proposals/edit_proposal.html', { 
        'proposal' : proposal,
        'form' : form })

@login_required
def delete_proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
    
    # redirect if submissions are not allowed or incorrect user
    if not proposal.theme.track.submissions_currently_allowed() or request.user != proposal.created_by:
        return redirect('review:proposal', pk = proposal.pk)

    # if valid post...
    if request.method == "POST":
        form = DeleteProposalForm(request.POST, instance = proposal)
        if form.is_valid():
            
            # delete the proposal
            proposal.delete()
            
            return redirect('review:theme', pk = proposal.theme.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = DeleteProposalForm(instance = proposal)
        
    return render(request, 'review/proposals/delete_proposal.html', { 
        'proposal' : proposal,
        'form' : form })

@login_required
def moderate_proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
        
    # redirect if user created the proposal or has already moderated it
    if request.user == proposal.created_by or request.user.moderation_requests.filter(proposal = proposal).first():
        return redirect('review:proposal', pk = proposal.pk)

    # if valid post...
    if request.method == "POST":
        form = ModerationRequestForm('proposal', request.POST)
        if form.is_valid():
            
            # save the moderation request
            moderation_request = form.save(commit = False)
            moderation_request.proposal = proposal
            moderation_request.requested_by = request.user
            moderation_request.save()
            
            # notify that moderation is required
            moderation_request.notify_staff(request)
            
            return redirect("review:proposal", pk = pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ModerationRequestForm('proposal')
    
    return render(request, 'review/proposals/moderate_proposal.html', {
        'proposal': proposal,
        'form' : form })
    
@login_required
def amendment(request, pk):
    amendment = get_object_or_404(Amendment, pk = pk)
    moderation = request.user.moderation_requests.filter(amendment = amendment).first()
     
    # if valid post...
    if request.method == 'POST':
        form = AmendmentForm(request.POST)
        if form.is_valid():        
                                        
            # cancel moderation if moderation request exists
            if 'cancel_moderation' in request.POST and moderation:
                moderation.delete()
                    
            # turn the moderation request into a comment
            if 'turn_moderation_into_comment' in request.POST and moderation:
                amendment.proposal.comments.create(
                    proposal = moderation.amendment.proposal, 

review/templates/review/support/faq.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Labour’s Democracy Review - Platform FAQ{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item active">Labour’s Democracy Review - Platform FAQ</li>
{% endblock %}

{% block content %}
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary mb-3">Back</a>
    
    <h4>Using My Momentum for the Democracy Review - FAQs</h4>
    <br/>
    
    <h6>a) What is the democracy review?</h6> 
    <p>After conference, the Labour Party launched the Democracy Review which will address a broad range of areas of party reform. By consulting with members, CLPS and trade union affiliates, Labour will canvass your opinion on how we can transform Labour into a 21st century, social movement style party.</p>
    <br/>

    <h6>b) Why is it important?</h6> 
    <p>The review is an unprecedented opportunity for ordinary members to input into the culture, rules and structure of the Labour Party, and to build a groundswell of support for a new kind of political party that can win the next election and transform Britain at every level.</p>
    <br/>

    <h6>c) Why should I submit my ideas to Momentum’s platform?</h6>
    <p>By submitting it into Momentum’s Digital Democracy Review platform, you will be able to generate a broader discussion of your ideas, and potentially build up a consensus of support behind them. If your ideas are then adopted as finalised Momentum submissions, they will be circulated to all members, who will be encouraged to submit them directly and through their CLPs, and will therefore be likely to obtain a higher number of submissions into the Review. Of course, participating in Momentum’s Digital Democracy Review does not prevent Momentum and Labour Party members from submitting the proposal into the Review directly.</p> 
    <br/>

    <h6>d) Do all proposals have to propose specific rule changes, and do they have to use ‘rule book’ language?</h6>
    <p>No. The most important thing is for the precise objective of the proposal to be clearly outlined, and good suggestions can of course be refined down the line in order to make them viable and bring them into line with the Rule Book if necessary. However, if members want to propose specific detailed rule changes, that is also fine.</p> 
    <br/>

    <h6>e) What are the moderating rules?</h6> 
    <p>All proposals, comments, and suggested amendments need to be in line with Momentum’s <a href="http://www.peoplesmomentum.com/ethics" target="_blank">Code of Ethics</a>, as well as being within the remit of the Democracy Review. Proposals contravening the Code of Ethics or which are clearly not attempts to advance serious discussions about party democracy will be removed. The moderation policy is available <a href="{% url 'review:moderation' %}">here</a>, and it is the collective responsibility of all Momentum members to ensure it is implemented by flagging up contributions which don’t adhere to these rules.</p>
    <br/>

    <h6>f) What if I am stuck for ideas for proposals?</h6> 
    <p>If you are stuck for ideas, contacting your local Momentum group or CLP to discuss, and please also see our <a href="{% static 'review/Democracy_Review_Ideas_from_Grassroots_Activists.pdf' %}">Ideas from Grassroots Activists</a> document. Rule changes which have been submitted by CLPs into the annual Labour Party Conference can also be re-submitted into Momentum’s <a href="{% url 'review:index' %}">Digital Democracy</a> platform if members want to ensure they are returned to the party reform agenda.</p>
    <br/>

    <h6>g) How many proposals can each member make?</h6>
    <p>Each member can make one proposal per theme.</p> 
    <br/>

    <h6>h) What is the point of the nominations system?</h6>
    <p>The point of the nominations system is to provide strong indications to the NCG and Momentum membership what the most popular proposals are.</p> 
    <br/>

    <h6>i) How many nominations does a proposal have to get to be considered seriously by the NCG?</h6>
    <p>All proposals will be considered, but proposals with high numbers of nominations will be given preference by the NCG, and their proposers will be directly consulted during the formulation of the finalised submissions before putting them to an all member ballot.</p> 
    <br/>

    <h6>j) Who decides which proposals get put the final OMOV vote?</h6> 
    <p>A panel of NCG representatives will decide which proposals get put to a final all member ballot. A staff member will consult the proposers of the most popular proposals in each theme on behalf of the NCG before drafting the finalised proposals. The NCG panel shall have authority to decide which parts of proposals are put into finalised submissions which are put to the vote.</p> 
    <br/>

    <h6>k) What happens to proposals once they are approved as official Momentum submissions?</h6> 
    <p>They will be sent to all Momentum members, who will be encouraged to submit them directly into the Democracy Review as individuals, as well as to pass them through their CLPs to submit into the Review.</p> 
    <br/>

    <h6>l) Why don’t proposals from the NCG or Members’ Council receive nominations?</h6> 
    <p>As the leading democratic body of Momentum and the key advisory body, proposals from the NCG and Members’ Council will automatically be considered by the NCG panel before being put to an OMOV Ballot. However, members can still suggest amendments to them and make comments on them.</p>
    <br/>

    <h6>m) What about submissions under Track 1 (BAME Labour, Young Labour, Women’s Conference)?</h6> 
    <p>The official deadline for Track 1 submissions passed on January 12th. However, CLPs can still submit proposals under Track 1 after that deadline, and discussions over the three themes will continue as well. For this reason, Momentum members can use the <a href="{% url 'review:index' %}">Digital Democracy</a> platform to suggest amendments to Momentum’s <a href="http://www.peoplesmomentum.com/democracy-review" target="_blank">recommended submissions</a> under these three areas.</p>
    <br/>

    <h6>n) How do local Momentum groups make submissions?</h6> 
    <p>At the launch of the platform, only individual members will be able to make proposals. However we are looking at allowing key contacts in each group to make proposals on behalf of groups. This functionality will be available shortly.</p>  
    <br/>

    <h6>o) Who is allowed to participate?</h6>
    <p>All Momentum members are allowed to participate. Members who breach the code of ethics or terms of Momentum’s constitution may have their access withdrawn.</p>
    <br/>

    <h6>p) I’ve had a really good idea but the deadline has passed. What should I do?</h6>
    <p>The deadline may have passed but the debate will continue! Please email your thoughts to <a href="mailto:transforminglabour@peoplesmomentum.com">transforminglabour@peoplesmomentum.com</a></p>  
 {% endblock %}

review/templates/review/support/guide.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Guide to Making a Proposal{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item active">Guide to Making a Proposal</li>
{% endblock %}

{% block content %}
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary mb-3">Back</a>
    
    <h4>Before making a proposal, please consider the following questions:</h4>
    <br/>

    <h6>a) Is my proposal relevant to the Democracy Review?</h6> 
    <p>Proposals should all be submitted within the <a href="{% static 'review/Democracy_Review_Explainer_to_Members.pdf' %}">current remit of the Democracy Review</a>. They should attempt to address broad issues and be relevant on a national scale. People who want to comment on experiences which are locally specific can make comments in the appropriate forum (e.g. people can comment on difficulties they have had in their CLPs in the comments section of the CLP Governance theme, rather than submitting a proposal on that basis.</p> 
    <br/>

    <h6>b) Has anyone already suggested something similar?</h6>
    <p>Because the objective of this process is to encourage a discussion about clear alternatives, members and groups should try to avoid duplicating efforts by other members, groups, the NCG or Members’ Council. If someone has already made a similar proposal to the one you would like to make, it might be better to suggest amendments to theirs rather than duplicating efforts.</p> 
    <br/>

    <h6>c) Can I express this proposal clearly and succinctly?</h6>
    <p>In order to make sure as many people as possible consider the content of your proposal, try to keep it as short as possible and make sure that its purpose is clearly expressed. Although it may be necessary to use legal jargon if you are advocating specific rule changes, make sure you make it clear in the supporting arguments what the meaning of that is.</p> 
    <br/>

    <h6>d) Have I picked the right theme to submit this proposal?</h6>
    <p>Try to make sure you submit your proposal under the correct theme in the Democracy Review remit. If you have any questions, write into <a href="mailto:transforminglabour@peoplesmomentum.com">transforminglabour@peoplesmomentum.com</a>.</p> 
    <br/>

    <h6>e) Am I choosing language that reflects the spirit of my proposal?</h6>
    <p>Please make sure that you choose language that reflects the inclusive and positive culture we would all like to see in the Labour Party. All proposals must be in line with Momentum’s <a href="http://www.peoplesmomentum.com/ethics" target="_blank">Code of Ethics</a>, and proposals which contravene this will be removed.</p> 

{% endblock %}

review/templates/review/support/help.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Help{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item active">Help</li>
{% endblock %}

{% block content %}
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary mb-3">Back</a>
    
    <h4>Technical help</h4>
    <p>Momentum members will receive an email from <a href="mailto:mymomentum@peoplesmomentum.com">mymomentum@peoplesmomentum.com</a> containing a single-use activation link.  Simply click on this link to start the activation of your My Momentum account, set a password and start using My Momentum.</p>
    <p>For technical issues please email: <a href="mailto:mymomentum@peoplesmomentum.com">mymomentum@peoplesmomentum.com</a></p>    
    <br/>

    <h4>Labour’s Democracy Review</h4>
    <p>Momentum have developed a <a href="{% url 'review:index' %}">digital platform</a> to generate ideas for submissions to the Labour Party Democracy Review, and allow members to comment on and upvote proposals they support. The aim is to enable a transparent debate between Momentum members, broaden our knowledge and discussion about party reform and ensure that Momentum’s submissions to the Democracy Review come from the grassroots of the movement.</p>
    <p>Please see our <a href="{% url 'review:rules' %}">guide on how the platform works</a>, or our more detailed <a href="{% url 'review:faq' %}">FAQs</a>.</p>
{% endblock %}

review/templates/review/support/rules.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Labour’s Democracy Review - How to use our platform{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item active">Labour’s Democracy Review - How to use our platform</li>
{% endblock %}

{% block content %}
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary mb-3">Back</a>
    
    <h4>How it works</h4>
    <p>Momentum members can use our <a href="{% url 'review:index' %}">Democracy Review</a> platform to: 1) Make proposals, 2) Make comments, 3) Propose amendments, 4) Make nominations, and 5) Vote on our final submissions.</p>
    <br/>

    <h6>1) Make Proposals</h6>
    <p>Proposals are any contributions which put forward any new ideas by members. Members can make one proposal per theme, and they can also be submitted by local Momentum groups, as well as by the National Coordinating Group (NCG) and the Members’ Council. Proposals must be made within certain deadlines (the deadline to make proposals for Track 3 submissions is midnight Friday 23rd March). Before making a proposal, please see <a href="{% url 'review:guide' %}">our recommendations for proposers</a>.</p>
    <br/>

    <h6>2) Make Comments</h6>
    <p>The purpose of comments is to allow members to express support, disagreement, or to share experiences and thoughts which are relevant to any given proposal. Any disagreements should be expressed in terms which are respectful and comradely.</p>
    <br/>

    <h6>3) Propose Amendments</h6>
    <p>Momentum members have the option of suggesting amendments to all proposals, including ones made by other members and groups, ones made by the National Coordinating Group (NCG) and Members’ Council, as well as Momentum’s recommended submissions for Track 1 (BAME Labour, Young Labour, and Women’s Conference). In all cases, the original proposers shall have authority over whether or not to accept amendments. For Track 3 submissions, the amendments shall be allowed anytime until midnight Friday 23rd March.</p>
    <br/>

    <h6>4) Make Nominations</h6>
    <p>The purpose of nominating in the Digital Platform is to give a clear indication to Momentum’s NCG which are the most popular proposals. Each Momentum member has one nomination in each of the 10 themes of Track 2 and Track 3 in the Democracy Review. They can nominate at anytime between Monday 29th January and Friday 16th February for Track 2 submissions, and anytime between Friday 2nd February and Friday 30th March for Track 3, and they can change their nominations as many times as they want to between those dates.</p>
    <br/>

    <h6>5) Final OMOV Ballots</h6>
    <p>The most popular proposals in each category will be submitted to Momentum’s National Coodinating Group (NCG). The final versions will then put to an OMOV Ballot of members, before being approved officially by Momentum.</p>
    <br/>

    <h6>Timeline</h6>
    <p>For a full timeline, please click <a href="{% static 'review/Democracy_Review_Timeline.pdf' %}" target="_blank">here</a>. We acknowledge that the deadlines for Track 2 are extremely tight, and would like to apologise for this. The reason is the importance of being able to circulate finalised submissions in time for activists to be able to pass them through CLPs before the 23rd March deadline.</p> 
    <br/>

    <h6>Any Questions?</h6>
    <p>Please see our <a href="{% url 'review:faq' %}">FAQs</a>.</p>
{% endblock %}