mxv/urls.py
from . import views
from . import forms
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse, HttpResponseRedirect

urlpatterns = [
    # landing page
    url(r'^$', views.index, name='index'),
    
    # admin
    url(r'^admin/', include('members.adminurls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),

    # redirect to react app    
    url(r'^app/', views.react),
    url(r'^api-auth/', include('rest_framework.urls')),

    # error testing
    url(r'^error/$', views.error, name='error'),
    
    # for various app urls.py

    # members
    url(r'^members/', include('members.urls')),
    url(r'^members/password_reset/$', views.ExtraContextPasswordResetView.as_view(
        form_class=forms.ActivationEmailPasswordResetForm), name='password_reset'),
    url(r'^members/login/$', auth_views.LoginView.as_view(
        form_class=forms.ActivationEmailAuthenticationForm), name='login'),
    url(r'^members/', include('django.contrib.auth.urls')),
    # q&a
    url(r'^questions/', include('questions.urls')),
    # lobbying 
    url(r'^lobby/', include('lobby.urls')),
    # groups
    url(r'^groups/', include('groups.urls')),
    # publications/petitions/cms
    url(r'^publications/', include('petitions.urls')),
    # democracy review
    url(r'^review/', include('review.urls')), 
    # GDPR
    url(r'^reconsent/$', views.reconsent, name='reconsent'), 
    url(r'^reconsent_complete/$', views.reconsent_complete, name='reconsent_complete'),
    # voting intentions
    url(r'^voting_intentions/', include('voting_intentions.urls')),
    # consultations
    url(r'^consultations/', include('consultations.urls')),
    # short URL redirects so that the links can be used in SMS
    url(r'^u/(?P<unique_token>[a-zA-Z0-9]+)/$',
        views.redirect_to_update_details, name='redirect_to_update_details'),

    # for martor, the markdown editor
    url(r'^martor/', include('martor.urls')),
    # task queueing
    url(r'^django-rq/', include('django_rq.urls')),

    # robots.txt
    url(r'^robots.txt', lambda x: HttpResponse(
        "User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),
    
    # humans.txt
    url(r'^humans.txt', lambda x: HttpResponseRedirect("https://gitlab.com/momentum-tech-collective/mxv")),

    # Imprint
    url(r'^imprint/', views.imprint)
]

if settings.PRIMARIES_VISIBLE:
    urlpatterns += [
        url(r'^primaries/', include('primaries.urls')),
    ]

admin.autodiscover()
admin.site.enable_nav_sidebar = False

review/urls.py
from django.conf.urls import url

from review import views

app_name = 'review'
urlpatterns = [
    # index
    url(r'^$', views.index, name='index'),
    #tracks
    url(r'^track/(?P<pk>\d+)/$', views.track, name = 'track'),
    # themes
    url(r'^theme/(?P<pk>\d+)/$', views.theme, name = 'theme'),
    # proposals
    url(r'^theme/(?P<pk>\d+)/new_proposal/$', views.new_proposal, name = 'new_proposal'),
    url(r'^theme/(?P<pk>\d+)/proposal_submitted/$', views.proposal_submitted, name = 'proposal_submitted'),
    url(r'^proposal/(?P<pk>\d+)/$', views.proposal, name = 'proposal'),
    url(r'^proposal/(?P<pk>\d+)/edit/$', views.edit_proposal, name = 'edit_proposal'),
    url(r'^proposal/(?P<pk>\d+)/delete/$', views.delete_proposal, name = 'delete_proposal'),
    url(r'^proposal/(?P<pk>\d+)/moderate/$', views.moderate_proposal, name = 'moderate_proposal'),
    # amendments
    url(r'^proposal/(?P<pk>\d+)/new_amendment/$', views.new_amendment, name = 'new_amendment'),
    url(r'^amendment/(?P<pk>\d+)/$', views.amendment, name = 'amendment'),
    url(r'^amendment/(?P<pk>\d+)/edit/$', views.edit_amendment, name = 'edit_amendment'),
    url(r'^amendment/(?P<pk>\d+)/delete/$', views.delete_amendment, name = 'delete_amendment'),
    url(r'^amendment/(?P<pk>\d+)/moderate/$', views.moderate_amendment, name = 'moderate_amendment'),
    # comments
    url(r'^proposal/(?P<pk>\d+)/new_comment/$', views.new_comment, name = 'new_comment'),
    url(r'^comment/(?P<pk>\d+)/$', views.comment, name = 'comment'),
    url(r'^comment/(?P<pk>\d+)/moderate/$', views.moderate_comment, name = 'moderate_comment'),
    # support pages
    url(r'^help/$', views.help, name = 'help'),
    url(r'^rules/$', views.rules, name = 'rules'),
    url(r'^faq/$', views.faq, name = 'faq'),
    url(r'^moderation/$', views.moderation, name = 'moderation'),
    url(r'^guide/$', views.guide, name = 'guide'),
    #track voting
    url(r'^voting/$', views.voting, name = 'voting'),
    url(r'^track_voting/(?P<pk>\d+)/$', views.track_voting, name = 'track_voting'),
    url(r'^track_voting/(?P<pk>\d+)/vote_submitted/$', views.vote_submitted, name = 'vote_submitted'),
]

review/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Track, Theme, Proposal, Amendment, Comment, TrackVoting
from django.db.models import Count, Q
from review.forms import EditProposalForm, ProposalForm, DeleteProposalForm, AmendmentForm, EditAmendmentForm, DeleteAmendmentForm, EditCommentForm, ModerationRequestForm, CommentForm, VoteForm
from django.contrib import messages
from datetime import date
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

@login_required
def index(request):
    today = date.today()
    live_tracks = Track.objects.order_by('display_order').filter(
        Q(submission_start__lte = today, submission_end__gte = today) | 
        Q(nomination_start__lte = today, nomination_end__gte = today))
    live_track_text = ''
    if live_tracks.count() == 1:
        live_track_text = ', with %s currently live' % live_tracks.first().name
    elif live_tracks.count() > 1:
        live_track_text = ', with %s currently live' % ' and '.join(track.name for track in live_tracks)
    return render(request, 'review/index.html', { 
        'tracks' : Track.objects.all().order_by('display_order'),
        'live_track_text': live_track_text,
        'track_votings': TrackVoting.objects.all() })

@login_required
def track(request, pk):
    track = get_object_or_404(Track, pk = pk)
    try:
        track_voting = track.voting
    except ObjectDoesNotExist:
        track_voting = None
    return render(request, 'review/tracks/track.html', { 
        'track' : track, 
        'themes': track.themes.order_by('display_order'),
        'show_voting': track_voting and track_voting.pk == 3 and (settings.TRACK3_VOTING_VISIBLE_TO_NON_STAFF or request.user.is_staff),
        'track_voting': track_voting })
    
@login_required
def theme(request, pk):
    theme = get_object_or_404(Theme, pk = pk)
    user_proposal = theme.proposals.filter(created_by = request.user).first()
    return render(request, 'review/themes/theme.html', { 
        'theme' : theme, 
        'proposals': theme.proposals.annotate(nomination_count = Count('nominations')).order_by('-nomination_count', '-created_at', 'pk'),
        'user_proposal': user_proposal })

@login_required
def proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
    moderation = request.user.moderation_requests.filter(proposal = proposal).first()
    
    # if valid post...
    if request.method == 'POST':
        form = ProposalForm(request.POST)
        if form.is_valid():        
            
            # nominate if allowed
            if 'nominate' in request.POST and proposal.theme.track.nominations_currently_allowed():
                for nomination in request.user.nominations.filter(proposal__theme = proposal.theme):
                    nomination.delete()
                proposal.nominations.create(proposal = proposal, nominated_by = request.user)
                
            # clear nomination if allowed
            if 'clear_nomination' in request.POST and proposal.theme.track.nominations_currently_allowed():
                nomination = proposal.nominations.filter(nominated_by = request.user, proposal = proposal).first()
                if nomination:
                    nomination.delete()
                    
            # cancel moderation if moderation request exists
            if 'cancel_moderation' in request.POST and moderation:
                moderation.delete()
                
            # turn the moderation request into a comment
            if 'turn_moderation_into_comment' in request.POST and moderation:
                proposal.comments.create(
                    proposal = moderation.proposal, 
                    created_by = moderation.requested_by, 
                    created_at = moderation.requested_at, 
                    text = moderation.reason)
                moderation.delete()
                    
            return redirect('review:proposal', pk = proposal.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ProposalForm(instance = proposal)

    return render(request, 'review/proposals/proposal.html', { 
        'proposal' : proposal,
        'proposal_urls' : proposal.urls.order_by('pk'),
        'amendments' : proposal.amendments.order_by('-created_at'),
        'comments' : proposal.comments.order_by('-created_at'),
        'user_nominated': request.user.nominations.filter(proposal = proposal).exists(),
        'moderation': moderation,
        'form': form })

@login_required
def new_proposal(request, pk):
    theme = get_object_or_404(Theme, pk = pk)
    
    # redirect if submissions are not allowed or user already has a proposal in this theme
    if not theme.track.nominations_currently_allowed() or request.user.proposals.filter(theme = theme).exists():
        return redirect('review:theme', pk = theme.pk)

    # if valid post...
    if request.method == "POST":
        form = EditProposalForm(request.POST)
        if form.is_valid():
            
            # create proposal
            proposal = form.save(commit = False)
            proposal.theme = theme
            proposal.created_by = request.user
            proposal.save()
            
            return redirect('review:proposal_submitted', pk = theme.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = EditProposalForm()
        
    return render(request, 'review/proposals/new_proposal.html', { 
        'theme' : theme,
        'form' : form })

@login_required
def proposal_submitted(request, pk):
    theme = get_object_or_404(Theme, pk = pk)
    return render(request, 'review/proposals/proposal_submitted.html', { 
        'theme' : theme })

@login_required
def edit_proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
    
    # redirect if moderated, submissions are not allowed or incorrect user
    if proposal.moderated() or not proposal.theme.track.submissions_currently_allowed() or request.user != proposal.created_by:
        return redirect('review:proposal', pk = proposal.pk)

    # if valid post...
    if request.method == "POST":
        form = EditProposalForm(request.POST, instance = proposal)
        if form.is_valid():
            
            # save the proposal
            proposal = form.save()
            
            return redirect('review:proposal', pk = proposal.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = EditProposalForm(instance = proposal)
        
    return render(request, 'review/proposals/edit_proposal.html', { 
        'proposal' : proposal,
        'form' : form })

@login_required
def delete_proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
    
    # redirect if submissions are not allowed or incorrect user
    if not proposal.theme.track.submissions_currently_allowed() or request.user != proposal.created_by:
        return redirect('review:proposal', pk = proposal.pk)

    # if valid post...
    if request.method == "POST":
        form = DeleteProposalForm(request.POST, instance = proposal)
        if form.is_valid():
            
            # delete the proposal
            proposal.delete()
            
            return redirect('review:theme', pk = proposal.theme.pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = DeleteProposalForm(instance = proposal)
        
    return render(request, 'review/proposals/delete_proposal.html', { 
        'proposal' : proposal,
        'form' : form })

@login_required
def moderate_proposal(request, pk):
    proposal = get_object_or_404(Proposal, pk = pk)
        
    # redirect if user created the proposal or has already moderated it
    if request.user == proposal.created_by or request.user.moderation_requests.filter(proposal = proposal).first():
        return redirect('review:proposal', pk = proposal.pk)

    # if valid post...
    if request.method == "POST":
        form = ModerationRequestForm('proposal', request.POST)
        if form.is_valid():
            
            # save the moderation request
            moderation_request = form.save(commit = False)
            moderation_request.proposal = proposal
            moderation_request.requested_by = request.user
            moderation_request.save()
            
            # notify that moderation is required
            moderation_request.notify_staff(request)
            
            return redirect("review:proposal", pk = pk)
        else:
            #show errors
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ModerationRequestForm('proposal')
    
    return render(request, 'review/proposals/moderate_proposal.html', {
        'proposal': proposal,
        'form' : form })
    
@login_required
def amendment(request, pk):
    amendment = get_object_or_404(Amendment, pk = pk)
    moderation = request.user.moderation_requests.filter(amendment = amendment).first()
     
    # if valid post...
    if request.method == 'POST':
        form = AmendmentForm(request.POST)
        if form.is_valid():        
                                        
            # cancel moderation if moderation request exists
            if 'cancel_moderation' in request.POST and moderation:
                moderation.delete()
                    
            # turn the moderation request into a comment
            if 'turn_moderation_into_comment' in request.POST and moderation:
                amendment.proposal.comments.create(
                    proposal = moderation.amendment.proposal, 

review/templates/review/amendments/amendment.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}{{ amendment.name }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:track' amendment.proposal.theme.track.pk %}">{{ amendment.proposal.theme.track.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:theme' amendment.proposal.theme.pk %}">{{ amendment.proposal.theme.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:proposal' amendment.proposal.pk %}">{{ amendment.proposal.name }}</a></li>
    <li class="breadcrumb-item active">{{ amendment.name }}</li>
{% endblock %}

{% block content %}
    <table class="card-text text-muted small">
        <tr><td><b>Created by</b></td><td>{{ amendment.created_by.name }}</td></tr>
        <tr><td><b>Created at</b></td><td>{{ amendment.created_at }}</td></tr>
        <tr class="{% if amendment.moderation_requests.count > 0 %}text-danger{% endif %}"><td><b>Moderation requests</b></td><td>{{ amendment.moderation_requests.count }}</td></tr>
    </table>
    <br>
    <form method="post" novalidate>
        {% csrf_token %}

        {% if not amendment.moderated %}
            {% include 'mxv/includes/form.html' %}
        {% else %}
            <p class="text-danger">Moderated.  Posts or comments that breach Momentum's code of ethics, or are not relevant to the Democracy Review's remit, will be removed.</p>
        {% endif %}
    
        {% if not amendment.moderated and not amendment.created_by.is_ncg and not amendment.created_by.is_members_council and amendment.created_by != user %}
            {% if not moderation %}
                <a href="{% url 'review:moderate_amendment' amendment.pk %}" class="btn btn-danger">Request moderation</a>
            {% else %}
                <br/>
                <p class="text-danger">You have requested moderation of this amendment for the following reason:</p>
                <blockquote class="blockquote">
                    <p class="text-danger small">{{ moderation.reason }}</p>
                </blockquote>
                <p class="text-danger">Only you and the moderator can see this moderation request.</p>
                <button type="submit" name="turn_moderation_into_comment" class="btn btn-success mr-4">Turn this into a comment instead</button>
                <button type="submit" name="cancel_moderation" class="btn btn-primary">Cancel moderation request</button>
            {% endif %}
        {% endif %}
    </form>    
    
    {% if amendment.proposal.theme.track.submissions_currently_allowed and amendment.created_by == user %}
        {% if not amendment.moderated %}
            <a href="{% url 'review:edit_amendment' amendment.pk %}" class="btn btn-success">Edit</a>
        {% endif %}
        <a href="{% url 'review:delete_amendment' amendment.pk %}" class="btn btn-danger">Delete</a>
    {% endif %}
    
{% endblock %}

review/templates/review/amendments/delete_amendment.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Delete{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:track' amendment.proposal.theme.track.pk %}">{{ amendment.proposal.theme.track.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:theme' amendment.proposal.theme.pk %}">{{ amendment.proposal.theme.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:proposal' amendment.proposal.pk %}">{{ amendment.proposal.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:amendment' amendment.pk %}">{{ amendment.name }}</a></li>
    <li class="breadcrumb-item active">Delete</li>
{% endblock %}

{% block content %}
    <div class="row card-text text-muted small">
        <div class="col-sm"><b>Created by:</b> {{ amendment.created_by.name }}</div>
        <div class="col-sm"><b>Created at:</b> {{ amendment.created_at }}</div>
    </div>
    <hr>
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'mxv/includes/form.html' %}
        <button type="submit" class="btn btn-danger">Delete this amendment?</button>
        <a href="{% url 'review:amendment' amendment.pk %}" class="btn btn-primary">Cancel</a>
    </form>    
{% endblock %}

review/templates/review/amendments/edit_amendment.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Edit{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:track' amendment.proposal.theme.track.pk %}">{{ amendment.proposal.theme.track.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:theme' amendment.proposal.theme.pk %}">{{ amendment.proposal.theme.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:proposal' amendment.proposal.pk %}">{{ amendment.proposal.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:amendment' amendment.pk %}">{{ amendment.name }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
{% endblock %}

{% block content %}
    <div class="row card-text text-muted small">
        <div class="col-sm"><b>Created by:</b> {{ amendment.created_by.name }}</div>
        <div class="col-sm"><b>Created at:</b> {{ amendment.created_at }}</div>
    </div>
    <hr>
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'mxv/includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'review:amendment' amendment.pk %}" class="btn btn-primary">Cancel</a>
    </form>    
{% endblock %}

review/templates/review/amendments/moderate_amendment.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}Request moderation{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:track' amendment.proposal.theme.track.pk %}">{{ amendment.proposal.theme.track.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:theme' amendment.proposal.theme.pk %}">{{ amendment.proposal.theme.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:proposal' amendment.proposal.pk %}">{{ amendment.proposal.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:amendment' amendment.pk %}">{{ amendment.name }}</a></li>
    <li class="breadcrumb-item active">Request moderation</li>
{% endblock %}

{% block content %}
    {% include "review/includes/moderation_text.html" %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'mxv/includes/form.html' %}
        <button type="submit" class="btn btn-danger">Request moderation</button>
        <a href="{% url 'review:amendment' amendment.pk %}" class="btn btn-primary">Cancel</a>
   </form>
{% endblock %}

review/templates/review/amendments/new_amendment.html
{% extends "mxv/base_nav.html" %}
{% load static %}

{% block title%}New amendment{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'review:index' %}">Democracy Review - Discuss</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:track' proposal.theme.track.pk %}">{{ proposal.theme.track.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:theme' proposal.theme.pk %}">{{ proposal.theme.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'review:proposal' proposal.pk %}">{{ proposal.name }}</a></li>
    <li class="breadcrumb-item active">New amendment</li>
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'mxv/includes/form.html' %}
        <button type="submit" class="btn btn-success">Create new amendment</button>
        <a href="{% url 'review:proposal' proposal.pk %}" class="btn btn-primary">Cancel</a>
   </form>
{% endblock %}